#!/usr/bin/env python3
"""Synthetic, network-free tests for the QSAR model validation helper CLIs.

Everything here runs against `fixtures/synthetic_actives.csv`, which is
generated by `fixtures/make_synthetic_actives.py` with a fixed seed.  The fixture
is built so that a compound's activity is decided by its Bemis-Murcko scaffold
family, which means the suite can assert the direction of the effect rather than
just that the code ran: a scaffold split must score worse than a random split,
and the leakage counts must be higher under the random split.  If those
assertions ever stop holding, the fixture or the split logic has changed, not
just the numbers.
"""

from __future__ import annotations

import contextlib
import csv
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[2] / "skills" / "qsar-model-validation"
SCRIPTS = SKILL_ROOT / "scripts"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
ACTIVES = FIXTURES / "synthetic_actives.csv"
sys.path.insert(0, str(SCRIPTS))

import _common  # noqa: E402
import applicability_domain  # noqa: E402
import calibration_report  # noqa: E402
import split_compare  # noqa: E402

import skill_contract  # noqa: E402


#: Every CLI that builds an argparse parser must answer `--help`.  `_common.py`
#: is a shared helper, not an entry point, and the contract skips it by name.
CliHelpTests = skill_contract.cli.help_test_case(SKILL_ROOT)


def _available(name: str) -> bool:
    """Report whether an optional scientific package can be imported."""

    try:
        __import__(name)
    except ImportError:
        return False
    return True


NEEDS_RDKIT = unittest.skipUnless(_available("rdkit"), "rdkit is not installed")
NEEDS_SKLEARN = unittest.skipUnless(
    _available("sklearn") and _available("numpy") and _available("pandas"),
    "scikit-learn, numpy, and pandas are needed",
)
#: Most of the suite needs the whole stack: structures to parse, arrays to hold
#: fingerprints, and a model to fit.
NEEDS_CHEM = unittest.skipUnless(
    _available("rdkit") and _available("sklearn") and _available("numpy")
    and _available("pandas"),
    "rdkit, scikit-learn, numpy, and pandas are needed",
)

#: Kept small so the suite stays quick; the assertions are about direction, not
#: about a particular value, so a weaker forest still demonstrates the point.
FAST = ["--n-estimators", "32", "--seeds", "0"]


def refusing_message(case: unittest.TestCase, entry_point, arguments: list[str]) -> str:
    """Run a CLI that must refuse its input and return what it said on stderr.

    The entry points catch ``CliError`` and turn it into exit code 2 with the
    reason on stderr, so a test that expects a refusal has to check both -- and
    the message, because "it failed" is not the same as "it failed for the
    stated reason".
    """

    captured = io.StringIO()
    with contextlib.redirect_stderr(captured):
        code = entry_point(arguments)
    case.assertEqual(
        code, 2, f"expected a refusal, got exit {code}; stderr was: {captured.getvalue()}"
    )
    return captured.getvalue()


class FixtureTests(unittest.TestCase):
    """The fixture has to stay what the other assertions assume it is."""

    def setUp(self) -> None:
        if not ACTIVES.is_file():
            self.skipTest("the synthetic fixture is missing")
        with ACTIVES.open(encoding="utf-8") as handle:
            self.rows = list(csv.DictReader(handle))

    def test_fixture_columns(self) -> None:
        self.assertEqual(
            sorted(self.rows[0]), ["pIC50", "series", "smiles", "year"]
        )

    def test_fixture_has_repeat_measurements(self) -> None:
        """The duplicate-collapsing path needs duplicates to exercise it."""

        structures = [row["smiles"] for row in self.rows]
        self.assertGreater(len(structures) - len(set(structures)), 0)

    @NEEDS_RDKIT
    def test_every_family_is_one_scaffold(self) -> None:
        """Otherwise the scaffold split is not holding out what it claims to."""

        from rdkit import Chem
        from rdkit.Chem.Scaffolds import MurckoScaffold

        families: dict[str, set[str]] = {}
        for row in self.rows:
            molecule = Chem.MolFromSmiles(row["smiles"])
            self.assertIsNotNone(molecule, f"unparseable fixture row: {row['smiles']}")
            families.setdefault(row["series"], set()).add(
                MurckoScaffold.MurckoScaffoldSmiles(mol=molecule)
            )
        for family, scaffolds in families.items():
            self.assertEqual(
                len(scaffolds), 1, f"{family} spans {len(scaffolds)} scaffolds"
            )
        self.assertGreater(len(families), 5)

    @NEEDS_RDKIT
    def test_every_fixture_structure_parses(self) -> None:
        from rdkit import Chem

        for row in self.rows:
            self.assertIsNotNone(Chem.MolFromSmiles(row["smiles"]), row["smiles"])


@NEEDS_SKLEARN
class SplitCompareTests(unittest.TestCase):
    """The claim the skill exists to support, asserted rather than described."""

    def run_cli(self, *extra: str) -> dict:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "report.json"
            code = split_compare.main(
                ["--input", str(ACTIVES), "--target-col", "pIC50", *FAST,
                 *extra, "--output", str(destination)]
            )
            self.assertEqual(code, 0)
            return json.loads(destination.read_text(encoding="utf-8"))

    def test_scaffold_split_scores_worse_than_random(self) -> None:
        document = self.run_cli("--task", "regression")
        comparison = document["comparison"]
        random_rmse = comparison["random"]["model_mean"]
        scaffold_rmse = comparison["scaffold"]["model_mean"]
        self.assertLess(
            random_rmse,
            scaffold_rmse,
            "the fixture is built so a random split looks better than a scaffold split; "
            "if this fails the fixture or the split logic changed",
        )
        self.assertGreater(comparison["scaffold"]["difference_vs_random"], 0)

    def test_random_split_leaks_more_than_scaffold_split(self) -> None:
        """The mechanism behind the gap: near-duplicates across the fold."""

        document = self.run_cli("--task", "regression")
        random_leak = document["splits"]["random"]["summary"]["near_duplicate_mean"]
        scaffold_leak = document["splits"]["scaffold"]["summary"]["near_duplicate_mean"]
        self.assertGreater(random_leak, scaffold_leak)
        self.assertEqual(
            document["splits"]["scaffold"]["summary"]["shared_scaffold_mean"], 0.0
        )

    def test_duplicate_structures_are_collapsed_and_reported(self) -> None:
        document = self.run_cli("--task", "regression")
        cleaning = document["cleaning"]
        with ACTIVES.open(encoding="utf-8") as handle:
            distinct = {row["smiles"] for row in csv.DictReader(handle)}
        self.assertGreater(cleaning["duplicate_structures_collapsed"], 0)
        self.assertEqual(cleaning["rows_used"], len(distinct))

    def test_group_split_matches_the_scaffold_result_on_this_fixture(self) -> None:
        """Each series is one scaffold here, so the two splits must agree."""

        document = self.run_cli("--task", "regression", "--group-col", "series")
        self.assertAlmostEqual(
            document["comparison"]["group"]["model_mean"],
            document["comparison"]["scaffold"]["model_mean"],
            places=6,
        )

    def test_time_split_is_reported(self) -> None:
        document = self.run_cli("--task", "regression", "--time-col", "year")
        self.assertIn("time", document["comparison"])
        self.assertEqual(document["columns"]["time"], "year")

    def test_classification_needs_an_explicit_threshold(self) -> None:
        """Choosing the cut here would manufacture a balanced problem."""

        message = refusing_message(self, split_compare.main, [
            "--input", str(ACTIVES), "--target-col", "pIC50",
            "--task", "classification", *FAST,
        ])
        self.assertIn("--active-threshold", message)

    def test_classification_reports_auc(self) -> None:
        document = self.run_cli(
            "--task", "classification", "--active-threshold", "6.5"
        )
        self.assertEqual(document["comparison"]["headline_metric"], "roc_auc")
        self.assertIsNotNone(document["comparison"]["random"]["model_mean"])
        self.assertIsNotNone(document["comparison"]["random"]["beats_dummy"])

    def test_the_dummy_baseline_is_always_reported(self) -> None:
        document = self.run_cli("--task", "regression")
        for strategy in ("random", "scaffold"):
            self.assertIsNotNone(
                document["comparison"][strategy]["baseline_mean"],
                f"the {strategy} split must carry a dummy baseline",
            )

    def test_repeated_seeds_report_a_range_not_just_a_mean(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "report.json"
            code = split_compare.main(
                ["--input", str(ACTIVES), "--target-col", "pIC50", "--task", "regression",
                 "--seeds", "0,1", "--n-estimators", "32", "--output", str(destination)]
            )
            self.assertEqual(code, 0)
            document = json.loads(destination.read_text(encoding="utf-8"))
        summary = document["splits"]["scaffold"]["summary"]
        self.assertEqual(summary["runs"], 2)
        self.assertLessEqual(summary["model_min"], summary["model_mean"])
        self.assertLessEqual(summary["model_mean"], summary["model_max"])

    def test_missing_column_is_an_error_not_a_guess(self) -> None:
        message = refusing_message(self, split_compare.main, [
            "--input", str(ACTIVES), "--target-col", "not_a_column", *FAST,
        ])
        self.assertIn("not_a_column", message)


@NEEDS_SKLEARN
class ApplicabilityDomainTests(unittest.TestCase):
    """The domain flag has to separate good predictions from bad ones."""

    def setUp(self) -> None:
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        rows = list(csv.DictReader(ACTIVES.open(encoding="utf-8")))
        seen: set[str] = set()
        unique = []
        for row in rows:
            if row["smiles"] in seen:
                continue
            seen.add(row["smiles"])
            unique.append(row)

        families = sorted({row["series"] for row in unique})
        held_out = set(families[-3:])
        self.train = [row for row in unique if row["series"] not in held_out]
        # The test half is deliberately mixed: compounds drawn from training
        # chemistry, plus every compound from the held-out families.
        drawn = self.train[::4]
        self.test = drawn + [row for row in unique if row["series"] in held_out]

        self._write("train.csv", self.train, include_prediction=False)
        self._write("test.csv", self.test, include_prediction=True)

    def _write(self, name: str, rows: list[dict], *, include_prediction: bool) -> None:
        """Write a split, with a prediction built to be good in-domain and poor out."""

        from rdkit import Chem
        from rdkit.Chem import rdFingerprintGenerator
        from sklearn.ensemble import RandomForestRegressor
        import numpy as np

        generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

        def features(items: list[dict]):
            return np.asarray([
                np.asarray(generator.GetFingerprint(Chem.MolFromSmiles(item["smiles"])))
                for item in items
            ])

        model = RandomForestRegressor(n_estimators=32, random_state=0, n_jobs=1)
        model.fit(features(self.train), [float(row["pIC50"]) for row in self.train])
        predictions = model.predict(features(rows))

        with (self.root / name).open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            header = ["smiles", "pIC50", "series"]
            if include_prediction:
                header.append("predicted")
            writer.writerow(header)
            for position, row in enumerate(rows):
                record = [row["smiles"], row["pIC50"], row["series"]]
                if include_prediction:
                    record.append(round(float(predictions[position]), 4))
                writer.writerow(record)

    def run_cli(self, *extra: str) -> dict:
        destination = self.root / "ad.json"
        code = applicability_domain.main([
            "--train", str(self.root / "train.csv"),
            "--test", str(self.root / "test.csv"),
            "--target-col", "pIC50",
            *extra,
            "--output", str(destination),
        ])
        self.assertEqual(code, 0)
        return json.loads(destination.read_text(encoding="utf-8"))

    def test_domain_split_is_produced_and_bounded(self) -> None:
        document = self.run_cli()
        summary = document["summary"]
        self.assertEqual(
            summary["inside_domain"] + summary["outside_domain"], summary["n_test"]
        )
        self.assertGreater(summary["outside_domain"], 0)

    def test_threshold_is_derived_from_the_training_set(self) -> None:
        document = self.run_cli()
        self.assertIn("percentile", document["threshold_source"])
        self.assertTrue(0.0 < document["threshold"] <= 1.0)

    def test_supplied_threshold_overrides_the_derived_one(self) -> None:
        document = self.run_cli("--threshold", "0.3")
        self.assertAlmostEqual(document["threshold"], 0.3)
        self.assertEqual(document["threshold_source"], "supplied with --threshold")

    def test_predictions_are_worse_outside_the_domain(self) -> None:
        """The point of the exercise, and the reason the flag is worth computing."""

        document = self.run_cli("--prediction-col", "predicted", "--task", "regression")
        by_domain = document["performance_by_domain"]
        inside = by_domain["inside_domain"]["rmse"]
        outside = by_domain["outside_domain"]["rmse"]
        self.assertLess(
            inside,
            outside,
            "the fixture holds out whole scaffold families, so out-of-domain error must "
            "exceed in-domain error",
        )
        self.assertTrue(
            any("RMSE is" in note for note in document["reading"]),
            "the report must state both errors rather than only the headline",
        )

    def test_prediction_column_without_a_target_is_refused(self) -> None:
        message = refusing_message(self, applicability_domain.main, [
            "--train", str(self.root / "train.csv"),
            "--test", str(self.root / "test.csv"),
            "--prediction-col", "predicted",
        ])
        self.assertIn("--target-col", message)

    @NEEDS_RDKIT
    def test_descriptor_range_method_runs(self) -> None:
        document = self.run_cli("--method", "descriptor-range")
        self.assertEqual(document["method"], "descriptor-range")
        self.assertTrue(
            all(
                entry["outside_by_descriptor_range"] is not None
                for entry in document["per_compound"]
            )
        )


@NEEDS_SKLEARN
class CalibrationReportTests(unittest.TestCase):
    """Calibration must change the magnitude and leave the ranking alone."""

    def setUp(self) -> None:
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        self.path = self.root / "probs.csv"
        self._build_probability_table()

    def _build_probability_table(self) -> None:
        """A deliberately under-confident model: ranks perfectly, probabilities wrong."""

        from rdkit import Chem
        from rdkit.Chem import rdFingerprintGenerator
        from sklearn.ensemble import RandomForestClassifier
        import numpy as np

        rows = list(csv.DictReader(ACTIVES.open(encoding="utf-8")))
        seen: set[str] = set()
        unique = []
        for row in rows:
            if row["smiles"] in seen:
                continue
            seen.add(row["smiles"])
            unique.append(row)

        generator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
        features = np.asarray([
            np.asarray(generator.GetFingerprint(Chem.MolFromSmiles(row["smiles"])))
            for row in unique
        ])
        labels = np.asarray([1 if float(row["pIC50"]) >= 6.5 else 0 for row in unique])
        model = RandomForestClassifier(
            n_estimators=25, max_depth=3, random_state=0, n_jobs=1
        ).fit(features, labels)
        probabilities = model.predict_proba(features)[:, 1]

        with self.path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["smiles", "label", "prob"])
            for row, label, probability in zip(unique, labels, probabilities):
                writer.writerow([row["smiles"], int(label), round(float(probability), 5)])

    def run_cli(self, *extra: str) -> dict:
        destination = self.root / "calibration.json"
        code = calibration_report.main([
            "--input", str(self.path),
            "--probability-col", "prob",
            "--label-col", "label",
            "--bins", "5",
            *extra,
            "--output", str(destination),
        ])
        self.assertEqual(code, 0)
        return json.loads(destination.read_text(encoding="utf-8"))

    def test_report_separates_calibration_from_evaluation_rows(self) -> None:
        document = self.run_cli()
        split = document["split"]
        self.assertEqual(
            split["calibration_rows"] + split["evaluation_rows"],
            180,
        )
        self.assertNotEqual(split["calibration_rows"], 0)
        self.assertNotEqual(split["evaluation_rows"], 0)

    def test_this_fixture_is_miscalibrated_but_ranks_well(self) -> None:
        """The premise of the calibration section, checked rather than assumed."""

        document = self.run_cli()
        uncorrected = document["evaluation"]["uncorrected"]
        self.assertGreater(uncorrected["ece"], 0.1)
        self.assertGreater(uncorrected["roc_auc"], 0.9)

    def test_isotonic_improves_calibration_without_changing_the_ranking(self) -> None:
        document = self.run_cli("--method", "isotonic")
        evaluation = document["evaluation"]
        self.assertLess(
            evaluation["corrected"]["ece"], evaluation["uncorrected"]["ece"]
        )
        self.assertAlmostEqual(
            evaluation["corrected"]["roc_auc"],
            evaluation["uncorrected"]["roc_auc"],
            places=9,
            msg="a monotone calibrator must not change ROC-AUC",
        )

    def test_platt_is_also_monotone(self) -> None:
        document = self.run_cli("--method", "platt")
        evaluation = document["evaluation"]
        self.assertAlmostEqual(
            evaluation["corrected"]["roc_auc"],
            evaluation["uncorrected"]["roc_auc"],
            places=9,
        )

    def test_calibration_column_reserves_rows_for_fitting(self) -> None:
        marked = self.root / "marked.csv"
        with self.path.open(encoding="utf-8") as source, marked.open(
            "w", newline="", encoding="utf-8"
        ) as destination:
            reader = csv.DictReader(source)
            writer = csv.writer(destination)
            writer.writerow([*reader.fieldnames, "fit"])
            for position, row in enumerate(reader):
                writer.writerow([*(row[name] for name in reader.fieldnames),
                                 "yes" if position % 2 == 0 else ""])

        output = self.root / "marked.json"
        code = calibration_report.main([
            "--input", str(marked),
            "--probability-col", "prob",
            "--label-col", "label",
            "--calibration-col", "fit",
            "--method", "isotonic",
            "--bins", "5",
            "--output", str(output),
        ])
        self.assertEqual(code, 0)
        document = json.loads(output.read_text(encoding="utf-8"))
        self.assertEqual(document["split"]["calibration_rows"], 90)
        self.assertIn("--calibration-col", document["split"]["source"])

    def test_a_single_class_is_refused(self) -> None:
        """Enough rows to reach the check, but only one outcome among them."""

        single = self.root / "single.csv"
        rows = "\n".join(f"{0.2 + 0.02 * index:.3f},1" for index in range(40))
        single.write_text(f"prob,label\n{rows}\n", encoding="utf-8")
        message = refusing_message(self, calibration_report.main, [
            "--input", str(single), "--probability-col", "prob", "--label-col", "label",
        ])
        self.assertIn("only one distinct outcome", message)

    def test_too_few_rows_is_refused_before_anything_else(self) -> None:
        tiny = self.root / "tiny.csv"
        tiny.write_text("prob,label\n0.2,1\n0.8,0\n", encoding="utf-8")
        message = refusing_message(self, calibration_report.main, [
            "--input", str(tiny), "--probability-col", "prob", "--label-col", "label",
        ])
        self.assertIn("at least 20", message)

    def test_out_of_range_probabilities_are_dropped_and_counted(self) -> None:
        """A score that is not a probability must not be read as one.

        Enough valid rows are kept that the report still runs, so this checks the
        counting rather than the row floor.
        """

        mixed = self.root / "mixed.csv"
        lines = ["prob,label"]
        for index in range(40):
            probability = 0.05 + 0.02 * index
            lines.append(f"{probability:.3f},{index % 2}")
        lines.extend(["1.700,1", "-0.400,0", "2.000,1"])
        mixed.write_text("\n".join(lines) + "\n", encoding="utf-8")

        destination = self.root / "mixed.json"
        code = calibration_report.main([
            "--input", str(mixed), "--probability-col", "prob", "--label-col", "label",
            "--bins", "5", "--output", str(destination),
        ])
        self.assertEqual(code, 0)
        document = json.loads(destination.read_text(encoding="utf-8"))
        self.assertEqual(document["rows_dropped"], 3)
        self.assertEqual(document["rows_in_file"], 43)


class CommonMetricTests(unittest.TestCase):
    """The metric definitions, checked against hand-computed values."""

    @NEEDS_SKLEARN
    def test_regression_metrics_on_a_worked_example(self) -> None:
        metrics = _common.regression_metrics([1.0, 2.0, 3.0], [1.0, 2.0, 3.0])
        self.assertAlmostEqual(metrics["rmse"], 0.0)
        self.assertAlmostEqual(metrics["mae"], 0.0)
        self.assertAlmostEqual(metrics["r2"], 1.0)
        self.assertAlmostEqual(metrics["rae"], 0.0)

        shifted = _common.regression_metrics([1.0, 2.0, 3.0], [2.0, 3.0, 4.0])
        self.assertAlmostEqual(shifted["rmse"], 1.0)
        self.assertAlmostEqual(shifted["mae"], 1.0)

    @NEEDS_SKLEARN
    def test_rae_uses_the_training_mean_when_given_one(self) -> None:
        """Using the test mean instead flatters a model on an unrepresentative set."""

        baseline_given = _common.regression_metrics(
            [1.0, 2.0, 3.0], [2.0, 2.0, 2.0], train_mean=10.0
        )
        baseline_absent = _common.regression_metrics([1.0, 2.0, 3.0], [2.0, 2.0, 2.0])
        self.assertNotAlmostEqual(baseline_given["rae"], baseline_absent["rae"])

    @NEEDS_SKLEARN
    def test_single_class_auc_is_none_rather_than_a_number(self) -> None:
        metrics = _common.classification_metrics([1, 1, 1], [0.2, 0.6, 0.9])
        self.assertIsNone(metrics["roc_auc"])
        self.assertIsNone(metrics["pr_auc"])
        self.assertEqual(metrics["n_positive"], 3)

    @NEEDS_SKLEARN
    def test_calibration_error_separates_good_from_bad(self) -> None:
        """A well-calibrated forecast scores far lower than a confident wrong one.

        The well-calibrated case here is 0.1 rather than 0.0, and that is not a
        defect: with equal-width bins a prediction of 0.9 lands in the bin whose
        centre is 0.9, and a perfectly calibrated 0.9 outcome rate still leaves a
        0.1 gap to the bin centre.  Equal-width ECE cannot fall below about
        1/(2 * bins) for extreme probabilities, which is why the reliability
        curve is reported alongside it.
        """

        good = _common.expected_calibration_error(
            [1, 0, 1, 0], [0.9, 0.1, 0.9, 0.1], bins=5
        )
        bad = _common.expected_calibration_error(
            [0, 0, 0, 0], [0.9, 0.9, 0.9, 0.9], bins=5
        )
        self.assertAlmostEqual(good["ece"], 0.1, places=6)
        self.assertGreater(bad["ece"], 0.8)
        self.assertLess(good["ece"], bad["ece"])

    @NEEDS_SKLEARN
    def test_reliability_curve_places_rows_in_their_bins(self) -> None:
        result = _common.expected_calibration_error(
            [1, 1, 0, 0], [0.05, 0.15, 0.85, 0.95], bins=2
        )
        self.assertEqual([entry["n"] for entry in result["curve"]], [2, 2])
        self.assertAlmostEqual(result["curve"][0]["observed_frequency"], 1.0)
        self.assertAlmostEqual(result["curve"][1]["observed_frequency"], 0.0)

    @NEEDS_SKLEARN
    def test_bootstrap_interval_brackets_the_point_estimate(self) -> None:
        import numpy as np

        rng = np.random.default_rng(0)
        truth = rng.normal(size=200)
        prediction = truth + rng.normal(scale=0.5, size=200)
        interval = _common.bootstrap_interval(
            lambda t, p: float(np.sqrt(np.mean((t - p) ** 2))),
            truth,
            prediction,
            resamples=200,
            seed=1,
        )
        self.assertLessEqual(interval["low"], interval["point"])
        self.assertLessEqual(interval["point"], interval["high"])
        self.assertEqual(interval["discarded"], 0)

    @NEEDS_CHEM
    def test_scaffold_split_never_shares_a_scaffold(self) -> None:
        rows = list(csv.DictReader(ACTIVES.open(encoding="utf-8")))
        smiles = sorted({row["smiles"] for row in rows})
        train, test = _common.scaffold_split_indices(smiles, test_size=0.25, seed=0)
        self.assertEqual(sorted(train + test), list(range(len(smiles))))
        scaffolds = _common.scaffolds_for(smiles)
        self.assertEqual(
            set(scaffolds[index] for index in train)
            & set(scaffolds[index] for index in test),
            set(),
        )

    @NEEDS_SKLEARN
    def test_group_split_keeps_every_group_whole(self) -> None:
        groups = [f"g{index // 3}" for index in range(30)]
        train, test = _common.group_split_indices(groups, test_size=0.25, seed=0)
        self.assertEqual(
            {groups[index] for index in train} & {groups[index] for index in test}, set()
        )

    @NEEDS_CHEM
    def test_a_single_scaffold_cannot_be_split_and_says_so(self) -> None:
        with self.assertRaises(_common.CliError) as caught:
            _common.scaffold_split_indices(
                ["c1ccccc1C", "c1ccccc1CC", "c1ccccc1CCC"], test_size=0.3, seed=0
            )
        self.assertIn("Bemis-Murcko", str(caught.exception))


class InputHandlingTests(unittest.TestCase):
    """Bad input is refused with a locatable reason, never guessed at."""

    def test_missing_file_names_the_path(self) -> None:
        with self.assertRaises(_common.CliError) as caught:
            _common.checked_input_file("/nonexistent/table.csv", label="the table")
        self.assertIn("/nonexistent/table.csv", str(caught.exception))

    def test_empty_file_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            empty = Path(directory) / "empty.csv"
            empty.write_text("", encoding="utf-8")
            with self.assertRaises(_common.CliError) as caught:
                _common.checked_input_file(empty, label="the table")
            self.assertIn("empty", str(caught.exception))

    def test_header_only_table_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            header = Path(directory) / "header.csv"
            header.write_text("smiles,pIC50\n", encoding="utf-8")
            with self.assertRaises(_common.CliError) as caught:
                _common.read_table(header)
            self.assertIn("no data rows", str(caught.exception))

    def test_fraction_converter_rejects_out_of_range(self) -> None:
        self.assertAlmostEqual(_common.fraction("0.25"), 0.25)
        for bad in ("0", "1", "1.5", "-0.2"):
            with self.assertRaises(_common.CliError):
                _common.fraction(bad)

    @NEEDS_RDKIT
    def test_unparseable_structures_are_reported_not_dropped_silently(self) -> None:
        canonical, problems = _common.canonicalize(["c1ccccc1", "not a molecule", ""])
        self.assertIsNone(canonical[1])
        self.assertIsNone(canonical[2])
        self.assertEqual(len(problems), 2)
        self.assertTrue(all("row" in problem for problem in problems))

    def test_emit_json_refuses_to_overwrite_without_force(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "report.json"
            _common.emit_json({"a": 1}, output=destination)
            with self.assertRaises(_common.CliError) as caught:
                _common.emit_json({"a": 2}, output=destination)
            self.assertIn("--force", str(caught.exception))
            _common.emit_json({"a": 3}, output=destination, force=True)
            self.assertEqual(
                json.loads(destination.read_text(encoding="utf-8")), {"a": 3}
            )


if __name__ == "__main__":
    unittest.main()
